object frm_Mailtest: Tfrm_Mailtest
  Left = 0
  Top = 0
  Caption = 'Mailtest'
  ClientHeight = 373
  ClientWidth = 635
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  Position = poScreenCenter
  OnClose = FormClose
  OnCreate = FormCreate
  OnDestroy = FormDestroy
  OnShow = FormShow
  PixelsPerInch = 96
  TextHeight = 13
  object PageControl1: TPageControl
    Left = 0
    Top = 0
    Width = 635
    Height = 373
    ActivePage = tbs_Mail
    Align = alClient
    TabOrder = 0
    object tbs_Mail: TTabSheet
      Caption = 'Mail'
      ExplicitLeft = 8
      ExplicitTop = 28
      object Panel1: TPanel
        Left = 0
        Top = 0
        Width = 627
        Height = 129
        Align = alTop
        BevelOuter = bvNone
        Caption = 'Panel1'
        ShowCaption = False
        TabOrder = 0
        object Panel2: TPanel
          Left = 0
          Top = 0
          Width = 56
          Height = 129
          Align = alLeft
          BevelOuter = bvNone
          Caption = 'Panel2'
          ShowCaption = False
          TabOrder = 0
          ExplicitTop = 1
          ExplicitHeight = 119
          object Label1: TLabel
            AlignWithMargins = True
            Left = 10
            Top = 25
            Width = 43
            Height = 13
            Margins.Left = 10
            Margins.Top = 25
            Align = alTop
            Caption = 'An:'
            ExplicitLeft = 40
            ExplicitTop = 24
            ExplicitWidth = 17
          end
          object Label2: TLabel
            AlignWithMargins = True
            Left = 10
            Top = 52
            Width = 43
            Height = 13
            Margins.Left = 10
            Margins.Top = 11
            Align = alTop
            Caption = 'CC:'
            ExplicitLeft = 39
            ExplicitTop = 43
            ExplicitWidth = 18
          end
          object Label3: TLabel
            AlignWithMargins = True
            Left = 10
            Top = 78
            Width = 43
            Height = 13
            Margins.Left = 10
            Margins.Top = 10
            Align = alTop
            Caption = 'BCC:'
            ExplicitLeft = 33
            ExplicitTop = 62
            ExplicitWidth = 24
          end
          object Label4: TLabel
            AlignWithMargins = True
            Left = 10
            Top = 104
            Width = 43
            Height = 13
            Margins.Left = 10
            Margins.Top = 10
            Align = alTop
            Caption = 'Betreff:'
            ExplicitLeft = 19
            ExplicitTop = 81
            ExplicitWidth = 38
          end
        end
        object Panel3: TPanel
          Left = 56
          Top = 0
          Width = 571
          Height = 129
          Align = alClient
          BevelOuter = bvNone
          Caption = 'Panel3'
          ShowCaption = False
          TabOrder = 1
          ExplicitHeight = 145
          object edt_Betreff: TEdit
            AlignWithMargins = True
            Left = 3
            Top = 101
            Width = 565
            Height = 21
            Align = alTop
            TabOrder = 0
            Text = 'edt_Betreff'
            ExplicitLeft = 216
            ExplicitTop = 39
            ExplicitWidth = 121
          end
          object edt_An: TEdit
            AlignWithMargins = True
            Left = 3
            Top = 20
            Width = 565
            Height = 21
            Margins.Top = 20
            Align = alTop
            TabOrder = 1
            Text = 'edt_An'
            ExplicitLeft = 2
            ExplicitTop = 9
            ExplicitWidth = 567
          end
          object edt_CC: TEdit
            AlignWithMargins = True
            Left = 3
            Top = 47
            Width = 565
            Height = 21
            Align = alTop
            TabOrder = 2
            Text = 'edt_An'
            ExplicitLeft = 216
            ExplicitTop = 39
            ExplicitWidth = 121
          end
          object edt_BCC: TEdit
            AlignWithMargins = True
            Left = 3
            Top = 74
            Width = 565
            Height = 21
            Align = alTop
            TabOrder = 3
            Text = 'edt_An'
            ExplicitLeft = 216
            ExplicitTop = 39
            ExplicitWidth = 121
          end
        end
      end
      object Panel4: TPanel
        Left = 0
        Top = 129
        Width = 56
        Height = 216
        Align = alLeft
        BevelOuter = bvNone
        Caption = 'Panel2'
        ShowCaption = False
        TabOrder = 1
        ExplicitTop = 1
        ExplicitHeight = 119
        object btn_Senden: TButton
          AlignWithMargins = True
          Left = 3
          Top = 3
          Width = 50
          Height = 25
          Align = alTop
          Caption = 'Senden'
          TabOrder = 0
          OnClick = btn_SendenClick
          ExplicitLeft = 0
          ExplicitTop = 16
          ExplicitWidth = 75
        end
      end
      object mem_Body: TMemo
        AlignWithMargins = True
        Left = 59
        Top = 132
        Width = 565
        Height = 210
        Align = alClient
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Courier New'
        Font.Style = []
        Lines.Strings = (
          'mem_Body')
        ParentFont = False
        TabOrder = 2
        ExplicitLeft = 62
        ExplicitTop = 128
        ExplicitWidth = 571
        ExplicitHeight = 216
      end
    end
    object tbs_Einstellung: TTabSheet
      Caption = 'Einstellung'
      ImageIndex = 1
      object Panel5: TPanel
        Left = 81
        Top = 0
        Width = 493
        Height = 345
        Align = alClient
        BevelOuter = bvNone
        Caption = 'Panel5'
        ShowCaption = False
        TabOrder = 0
        ExplicitLeft = 84
        object Edt_SMTP: TEdit
          AlignWithMargins = True
          Left = 3
          Top = 10
          Width = 487
          Height = 21
          Margins.Top = 10
          Align = alTop
          MaxLength = 80
          TabOrder = 0
          ExplicitLeft = 61
          ExplicitTop = 33
          ExplicitWidth = 200
        end
        object Edt_User: TEdit
          AlignWithMargins = True
          Left = 3
          Top = 37
          Width = 487
          Height = 21
          Align = alTop
          MaxLength = 80
          TabOrder = 1
          ExplicitLeft = 61
          ExplicitTop = 58
          ExplicitWidth = 200
        end
        object Edt_Passwort: TEdit
          AlignWithMargins = True
          Left = 3
          Top = 91
          Width = 487
          Height = 21
          Align = alTop
          MaxLength = 40
          PasswordChar = '*'
          TabOrder = 2
          ExplicitLeft = 61
          ExplicitTop = 83
          ExplicitWidth = 200
        end
        object edt_Port: TEdit
          AlignWithMargins = True
          Left = 3
          Top = 118
          Width = 487
          Height = 21
          Align = alTop
          MaxLength = 40
          TabOrder = 3
          ExplicitTop = 91
        end
        object cbo_TLS: TComboBox
          AlignWithMargins = True
          Left = 3
          Top = 145
          Width = 487
          Height = 21
          Align = alTop
          Style = csDropDownList
          TabOrder = 4
          Items.Strings = (
            'Verwenden (NoTLSSupport)'
            'Explizit verwenden (UseExplicitTLS)'
            'Impliziert verwenden (UseImplicitTLS)'
            'Ben'#246'tigt (UseRequireTLS)')
          ExplicitLeft = 130
          ExplicitTop = 131
          ExplicitWidth = 95
        end
        object cbo_AuthType: TComboBox
          AlignWithMargins = True
          Left = 3
          Top = 172
          Width = 487
          Height = 21
          Align = alTop
          Style = csDropDownList
          TabOrder = 5
          Items.Strings = (
            'Verwenden (NoTLSSupport)'
            'Explizit verwenden (UseExplicitTLS)'
            'Impliziert verwenden (UseImplicitTLS)'
            'Ben'#246'tigt (UseRequireTLS)')
          ExplicitLeft = 82
          ExplicitTop = 163
          ExplicitWidth = 95
        end
        object cbo_SSLVersion: TComboBox
          AlignWithMargins = True
          Left = 3
          Top = 199
          Width = 487
          Height = 21
          Align = alTop
          Style = csDropDownList
          TabOrder = 6
          Items.Strings = (
            'Verwenden (NoTLSSupport)'
            'Explizit verwenden (UseExplicitTLS)'
            'Impliziert verwenden (UseImplicitTLS)'
            'Ben'#246'tigt (UseRequireTLS)')
          ExplicitLeft = 98
          ExplicitTop = 188
          ExplicitWidth = 95
        end
        object edt_AbsMail: TEdit
          AlignWithMargins = True
          Left = 3
          Top = 64
          Width = 487
          Height = 21
          Align = alTop
          MaxLength = 40
          TabOrder = 7
        end
      end
      object Panel6: TPanel
        Left = 0
        Top = 0
        Width = 81
        Height = 345
        Align = alLeft
        BevelOuter = bvNone
        Caption = 'Panel5'
        ShowCaption = False
        TabOrder = 1
        object Label192: TLabel
          AlignWithMargins = True
          Left = 10
          Top = 14
          Width = 68
          Height = 13
          Margins.Left = 10
          Margins.Top = 14
          Align = alTop
          Caption = 'Server:'
          Font.Charset = ANSI_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentFont = False
          ExplicitLeft = 11
          ExplicitTop = 15
          ExplicitWidth = 66
        end
        object Label193: TLabel
          AlignWithMargins = True
          Left = 10
          Top = 40
          Width = 68
          Height = 13
          Margins.Left = 10
          Margins.Top = 10
          Align = alTop
          Caption = 'Benutzer:'
          ExplicitLeft = 7
          ExplicitTop = 61
          ExplicitWidth = 47
        end
        object Label5: TLabel
          AlignWithMargins = True
          Left = 10
          Top = 96
          Width = 68
          Height = 13
          Margins.Left = 10
          Margins.Top = 12
          Align = alTop
          Caption = 'Passwort:'
          ExplicitLeft = 13
          ExplicitTop = 68
          ExplicitWidth = 66
        end
        object lbl_MailPort: TLabel
          AlignWithMargins = True
          Left = 10
          Top = 123
          Width = 68
          Height = 13
          Margins.Left = 10
          Margins.Top = 11
          Align = alTop
          Caption = 'Port:'
          ExplicitLeft = 13
          ExplicitTop = 88
          ExplicitWidth = 66
        end
        object Label11: TLabel
          AlignWithMargins = True
          Left = 10
          Top = 150
          Width = 68
          Height = 13
          Margins.Left = 10
          Margins.Top = 11
          Align = alTop
          Caption = 'TLS:'
          ExplicitLeft = 14
          ExplicitTop = 125
          ExplicitWidth = 21
        end
        object Label12: TLabel
          AlignWithMargins = True
          Left = 10
          Top = 177
          Width = 68
          Height = 13
          Margins.Left = 10
          Margins.Top = 11
          Align = alTop
          Caption = 'Auth.-Type:'
          ExplicitLeft = 14
          ExplicitTop = 190
          ExplicitWidth = 59
        end
        object Label13: TLabel
          AlignWithMargins = True
          Left = 10
          Top = 204
          Width = 68
          Height = 13
          Margins.Left = 10
          Margins.Top = 11
          Align = alTop
          Caption = 'SSL-Version:'
          ExplicitLeft = 37
          ExplicitTop = 263
          ExplicitWidth = 60
        end
        object Label6: TLabel
          AlignWithMargins = True
          Left = 10
          Top = 68
          Width = 68
          Height = 13
          Margins.Left = 10
          Margins.Top = 12
          Align = alTop
          Caption = 'Absender Mail:'
          ExplicitWidth = 71
        end
      end
      object Panel7: TPanel
        Left = 574
        Top = 0
        Width = 53
        Height = 345
        Align = alRight
        BevelOuter = bvNone
        Caption = 'Panel7'
        ShowCaption = False
        TabOrder = 2
      end
    end
  end
end
